#!/bin/bash

PROGRAM=$1

source ~/.$PROGRAM/venv/bin/activate
echo -ne "\n"
pip list --format=columns > venv_installed.txt
./list2req.py venv_installed.txt venv_requirements.txt
./venv_create $PROGRAM
deactivate
